### ISSUE TITLE
Consider grouping some categories by "topic" instead of alphabetical

### ISSUE THREAD

**Issue by charparr** [ua-snap/arctic-eds#132]
Consider groups like so:
![image](https://user-images.githubusercontent.com/7774271/174850400-1c1bb191-8263-48d2-9c3b-cb979b042730.png)

**Comment by BobTorgerson** [comment]
Do we want to do the ordering this way or as in #150 ?

**Comment by brucecrevensten** [comment]
Xref also #14

**Comment by BobTorgerson** [comment]
No longer relevant in new iteration of Arctic EDS.
