### ISSUE TITLE
Change text to remove "science" from the homepage blurb

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#134]
Right now the home page side blurb says "Modern environmental data for science and engineering." -- consider changing that to remove "science" or at least put "engineering" first to emphasize the engineering aspect?

**Comment by charparr** [comment]
This is done. Home page call to action currently reads:
```
Use Arctic-EDS to query historical, current and projected environmental data for engineering applications.
Download data or use our computational notebooks for analysis.
```
Nice.
