### ISSUE TITLE
Fix Tinted Colored Borders at Edges of Map Views

### ISSUE THREAD

**Issue by charparr** [ua-snap/arctic-eds#144]
Plates Where This is Embarrassing

- Permafrost
- Temperature
- Precipitation
- Snowfall
- FI
- Design FI
- TI
- Design TI
- HDD

**Comment by BobTorgerson** [comment]
This is fixed by the upstream Rasdaman fixes, we need to update Zeus's version of Rasdaman to fix this. We confirmed the fix on Apollo already.

**Comment by brucecrevensten** [comment]
Fixed / deployed, closing.
