### ISSUE TITLE
Minor homepage and About section edits

### ISSUE THREAD

**Issue by carolynrosner** [ua-snap/arctic-eds#145]
Alpha list for links under "Physiography"
Remove hyphens from "readily-available" and "high-quality"
Remove "and vetted' ? This feels redundant, coming after "curated" -- curated means vetted, really.

About section: can all links be orange, like on home page? Maybe it's fine that just home page links are orange...

Climate models page: Remove extra period after "... RCP 8.5 are good choices" in the "Best practices" section.

**Comment by BobTorgerson** [comment]
We've had major updates to the home page and this needs to be re-evaluated for accuracy in the ticket now.

**Comment by brucecrevensten** [comment]
Agree with Bob; closing this, we have more work to do on the homepage but this ticket doesn't really apply to the new layout.
