### ISSUE TITLE
Consider changing the navigation order of Engineering pages

### ISSUE THREAD

**Issue by MikeDelue** [ua-snap/arctic-eds#150]
From an overview with an outside friend it became clear to me that we haven't ordered the plates under Engineering in the most intuitive way. For a user who knows what they want it doesn't much matter but for the ley-user we should consider ordering the plates from least to most derived.

Suggested order

1. Freezing Index
2. Thawing Index
3. Design Freezing Index
4. Design Thawing Index
5. Heating Degree Days

**Comment by brucecrevensten** [comment]
I agree, let's not do this alphabetically because it doesn't make as much sense for these categories.  Let's implement this with the home page remix work #14 and friends.

**Comment by BobTorgerson** [comment]
No longer relevant with new iteration of the Arctic EDS.
