### ISSUE TITLE
Allow users to enter lat/lon coordinates like 64.84° N, 147.72° W instead of 64.84, -147.72

### ISSUE THREAD

**Issue by cstephen** [ua-snap/arctic-eds#161]
The lat/lon input will not allow users to enter longitude values that are not negative, which excludes this alternate way of writing the lat/lon for Fairbanks, for example:

> 64.84° N, 147.72° W

I don't think it will be very hard to make this happen, but an alternative is to tell users how they need to enter lat/lon.

Similar to ticket #159, this ticket may end up getting fixed a different/better way by copying over parts of the location selector from NCR described in #115.

**Comment by brucecrevensten** [comment]
Xref #115 and #8, this should be solved by incorporating the control from NCR.

**Comment by cstephen** [comment]
Closed by #211 and subsequent PRs.
