### ISSUE TITLE
Create before/after illustrations for the About page

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#167]
Idea is to incorporate a before (from the old Atlas) with an after image from the new Atlas.  This should be done as a composed graphic to make it look good, with appropriate legend/etc incorporate in the new image.

**Comment by brucecrevensten** [comment]
OK, I like this idea but I don't see where it fits and I kinda feel like we're past this in terms of needing it as part of any design work.  Closing.

**Comment by carolynrosner** [comment]
Agree. Neat idea, but I think we're good for design elements here.
