### ISSUE TITLE
Remove UserPrompt component

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#174]
We accidentally both did the same thing and there's two components which nudge the user to engage with the map.  Check the UserPrompt component (it's got a smarter way of notifying the user about the result of their action) and meld it with the PlateInstructions component, then remove the UserPrompt one.

Expected outcomes:

- There's only a single component that does this (not two with near-identical functionality).

**Comment by cstephen** [comment]
Looks like the unused `UserPrompt` component was either lost in the shuffle or resurrected somewhere along the way. It still needs to be removed, so keeping this ticket open.

**Comment by brucecrevensten** [comment]
It's gone!
