### ISSUE TITLE
Edit design thawing index language

### ISSUE THREAD

**Issue by charparr** [ua-snap/arctic-eds#180]
Use "three coldest years" which matches the language used for thawing index and makes it more clear what data are presented.

https://github.com/ua-snap/arctic-eds/blob/5a6e288ba998a4c5af7c9f2ddaa08028ba63c1a7/pages/engineering/design-freezing-index.vue#L9

**Comment by charparr** [comment]
Explicitly name what values are provided by the app table and the CSV.

For the table:
 - For each of these two models (both RCP 8.5), we collected every annual (30) freezing index value for this location in the time era indicated. The three coldest years (greatest freezing index values) were identified. The design freezing index value for each model was computed by finding the mean of those three values. The values you see here are the average of the design freezing index values from each model.

**Comment by BobTorgerson** [comment]
Text integrated into newest version of the Arctic EDS report
