### ISSUE TITLE
Units in Design Freezing Index downloads / units

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#193]
This may be relevant for other degree day / index calculation too.  This ticket may need to be solved elsewhere (if at all) and this may be a non-issue, but: **what units are the downloaded CSVs for Design Freezing Index in?**

 * The downloaded CSV needs a clearer labeling of units (not just "above freezing").
 * From the user interface, the assumption would be that it's in ºF because the numbers match.  But, often our downloaded CSVs are in metric units.  It's not clear to me from the API code if/where the conversion is happening, or if the conversion was done in the data layer (in which case, documentation in the API would be good).

Opening this ticket here in case it turns out that we need to change things on this end.

**Comment by charparr** [comment]
XREF #287

**Comment by brucecrevensten** [comment]
This looks good in current revs (for degree days, etc) -- units are labeled, etc.
