### ISSUE TITLE
Add Elevation, Geology, Ecoregion to introduction as inline text

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/arctic-eds#237]
Add Elevation, Geology, Ecoregion to introduction as inline text (with links out to the best online resource for Ecoregion classifications + the USGS Geology map). Read the NCR report intro for motivation for how to do this.

Complete as part of #236

**Comment by brucecrevensten** [comment]
Complete!  Will need more revision, and in particular we may want to consider removing geology/ecoregion altogether (unsure) and also perhaps making elevation cover a 20km pixel instead of 1km.
