### ISSUE TITLE
Provide guidance on how to actually work with and use these data in context.

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#286]
We know that users of these data from the engineering audience could benefit from some specifics on how to approach these types of datasets.  To this end, let's consider a primer that is concise and geared towards what the audiences may want to do.  For example:

1. Look at the model projection data
2. Then, look at the historical baseline associated with that dataset to understand how those projections are a departure from current or historical conditions.
3. Bias correct both of those things to your particular station of interest
4. Compare gridded futures to gridded past, and then fine tune both of them with point observations.

..etc.

**Comment by charparr** [comment]
I don't think this is must have - we could expand some of the above points and add it to some documentation somewhere?
However - I thiiiink we have a notebook with this flow already, and if so, we can plug and play that into a module rather easily I think. Pinging @kyleredilla do you remember if a notebook has this kind of bias-correction with station data baked in somewhere?

**Comment by kyleredilla** [comment]
Ahh nothing is coming to mind! I did some bias correction stuff for John with the wind work, but that was in R. It might be low friction to try out [xclim for this](https://xclim.readthedocs.io/en/stable/sdba.html)!

**Comment by charparr** [comment]
Closed by #428
