### ISSUE TITLE
De-summarize Design Thawing/Freezing Index Tables?

### ISSUE THREAD

**Issue by charparr** [ua-snap/arctic-eds#287]
The design thawing index values in the table that is presented in the app are averaged across two models. However, when you download the CSV data from the app, you get a different set of values in which the models are separated out. But, it isn’t really clear anywhere in the app that the results in the app table are the mean of the two design index values that are seen in the CSV data. I think this is a case where we are “hiding the complexity” but just making it more confusing. For this audience I recommend showing the CSV data in the app: 5 design index values, one per era and model, plus the ERA-Interim historical.

Here is an example: these data

![image](https://github.com/ua-snap/arctic-eds/assets/7774271/6347330d-6bcd-42aa-98c0-57c6d959499c)

 are the means of the two models in this data:
 
![image](https://github.com/ua-snap/arctic-eds/assets/7774271/19d17799-e1fd-434a-8718-fe1c0fb88623)

**Comment by brucecrevensten** [comment]
Design indices are moving into modules, closing this ticket.
