### ISSUE TITLE
Page jumps to top when closing a map

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#297]
STR:

 * Load home page, scroll down, click on one of the maps
 * See the popup window!
 * Close the popup window.

Expected: you're where you were on the page.
Actual: it bounces you back up to the top.

We can just have this target a new anchor just above the maps, that'd work.

**Comment by cstephen** [comment]
This issue is no longer applicable since the maps have been de-modal-ized.
