### ISSUE TITLE
UX feedback

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#3]
(1) Add range of valid lat/lngs to the selector,
(2) Tighten up spacing when a report is active (there's a huge whitespace above right now)
(3) Make the spacing between map/footer more sensible
(4) change link color to be colorblind-safe

**Comment by BobTorgerson** [comment]
Some of these are already other tickets, some should be made into their own tickets if we want to move forward with them.

**Comment by brucecrevensten** [comment]
I think all of these are either done or should be added as new tickets upon revised layout/other changes.
