### ISSUE TITLE
Consider calculating and serving the CSV preview sizeBlurb dynamically from the API instead of hard-coding it

### ISSUE THREAD

**Issue by cstephen** [ua-snap/arctic-eds#316]
This would eliminate the risk of the CSV sizeBlurbs in Arctic EDS falling out of sync with the actual CSV files from the API, if the CSVs from the API get changed somewhere along the way. However, this may have significant performance penalties, so it is not an obvious win.

**Comment by charparr** [comment]
I'm going to close this, it's fun to have the CSV file size but I'm not sure how much our end users need accurate sizes, especially when most of them are in `kb` range.
