### ISSUE TITLE
Integrate links to modules

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#322]

**Comment by charparr** [comment]
Here are what the direct links to the individual notebooks look like:

Design Discharge
https://ua-snap.github.io/ardac-notebooks/lab?path=design_discharge%2Fdesign_discharge.ipynb

Design Freezing Index
https://ua-snap.github.io/ardac-notebooks/lab?path=design_freezing_index%2Fdesign_freezing_index_module.ipynb

Design Thawing Index
https://ua-snap.github.io/ardac-notebooks/lab?path=design_thawing_index%2Fdesign_thawing_index_module.ipynb

Modified Berggren Frost Depth
https://ua-snap.github.io/ardac-notebooks/lab?path=frost_depth%2FModified+Berggren+Frost+Depth.ipynb
