### ISSUE TITLE
Provide direct links to datasets/deeper level of detail from maps?

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#371]
>  Is there a way to provide users a link to the datasets provided in the climate maps section? I have no idea if this makes sense, but I was wondering if some users might go straight to the climate maps and want to [...] click on a link that takes you to the dataset.

**Comment by charparr** [comment]
XREF #410 

But closing because we declare at the top of the maps page "these maps aren't interactive" and I think in this case we don't want users bypassing the report page with all the disclaimers about uncertainty, etc.
