### ISSUE TITLE
Add intro text to Climate Maps page

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#372]

**Comment by carolynrosner** [comment]
### Statewide Climate Overview Maps

See an Alaska-wide view of historical and projected climate-related environmental variables. To see community-based data, **visit the home page** and choose a location. 


![Screenshot 2023-10-13 at 11 41 02 AM](https://github.com/ua-snap/arctic-eds/assets/5123589/b1534161-389c-4d52-830a-9ec9cc8a03cb)

**Comment by brucecrevensten** [comment]
I went with a slight remix of this, 

```
See an Alaska-wide view of historical and projected climate-related environmental variables.  To see all available data for a point, go to the home page and choose a community or latitude/longitude.
```
