### ISSUE TITLE
Switch Hydrology summaries to be annual totals, not means

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#378]
> We may want our preview tables to be mmm annual totals, rather than annual means. Then runoff and evap become (inches per year).

**Comment by brucecrevensten** [comment]
Or not!  I've removed the summary tables entirely for the time being.  Keeping this ticket around in case we do choose to restore them.

**Comment by charparr** [comment]
I'm OK with no summary tables because there are so many variables in this section and because they'd need to be summarized by month, and you'd have to pick months that are useful (e.g., for SWE, choose May), so I don't think the juice is worth the squeeze here.
