### ISSUE TITLE
Make spatial resolution text refer to total grid cell area

### ISSUE THREAD

**Issue by charparr** [ua-snap/arctic-eds#416]
Instead of `Spatial Resolution: 12 km` use `Grid Cell Area: 144 km**2` but you know, superscript style

**Comment by brucecrevensten** [comment]
I think we'd want both; depending on someone's universe, one or the other may make more sense (for example GeoNetwork explicitly wants "spatial resolution").

**Comment by charparr** [comment]
I think we've converged here on language like "the spatial resolution (grid cell size) of all data is 771 m by 771 m" which is explicit enough. If someone screams at us then we can change it. Closing.
