### ISSUE TITLE
Update temperate indices sections with new intro/summary text and CSV rows/columns/size blurbs to reflect API degree days update

### ISSUE THREAD

**Issue by cstephen** [ua-snap/arctic-eds#420]
We'll need to update Arctic-EDS to reflect the major changes to the degree days API endpoints captured in this PR:

https://github.com/ua-snap/data-api/pull/428

Changes include:

- New/different models
- More scenarios
- One more CSV column & many more CSV rows
- Much bigger CSV file sizes (mentioned at the bottom of the CSV preview tables)

**Comment by charparr** [comment]
This looks done to me! e.g., https://arcticeds.org/report/community/AK73#temperature-indices
Closing.
