### ISSUE TITLE
Non-sequitur in paragraph about pixel size / elevation

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#430]
> Grid cell size may vary by a factor of up to 250x. Please keep this in mind when interpreting a variable for a given location. For example, the elevation within 1 km of Utqiaġvik (Barrow), Alaska, centered at 71.2905, -156.789, ranges between 0–18 meters, with an average elevation of 6 meters. This variation should be kept in mind when interpreting the variables below. 

Could instead be,

> Grid cell size may vary by a factor of up to 250x. Please keep this in mind when interpreting a variable for a given location.

> Variation in altitude within a grid cell impacts its value.  For example, the elevation within 1 km of Utqiaġvik (Barrow), Alaska, centered at 71.2905, -156.789, ranges between 0–18 meters, with an average elevation of 6 meters. This variation should be kept in mind when interpreting the variables below.

**Comment by charparr** [comment]
Still valid and I'm in favor of the whitespace separation as elevation and grid cell size are indeed separate but related uncertainty sources.

**Comment by BobTorgerson** [comment]
This has been resolved as of the April updates to ArcticEDS and has in fact been deployed to the live site already: https://github.com/ua-snap/arctic-eds/pull/422
