### ISSUE TITLE
Scrutinize coastal ring on freezing/thawing index map layers (and probably other Engineering plates)

### ISSUE THREAD

**Issue by cstephen** [ua-snap/arctic-eds#54]
Shows up in projected data and not historical data. May need to ask Peter and Rick about this sharp transition. There are fainter spots in inland Alaska that exhibit this same behavior.

**Comment by charparr** [comment]
All of the temperature indices have pretty much been re-styled in the most recently deployed version. Coastal "ringing" is not pronounced, and based on the analysis in this ticket discussion, this was likely a "real" representation of the underlying data anyway.
