### ISSUE TITLE
Consider swapping hierarchy of Bulma's section & container classes

### ISSUE THREAD

**Issue by cstephen** [ua-snap/arctic-eds#64]
When using `section` and `container` together, we have been consistently structuring them like this:

```
<div class="container">
  <section class="section">
    ...
  </section>
</div>
```

The [documentation](https://bulma.io/documentation/layout/container/) suggests that the hierarchy should normally be in the other order:

```
<section class="section">
  <div class="container">
    ...
  </div>
</section>
```
Although it is not clear if our approach is technically wrong, just unusual. If we can achieve the same effect the "normal" way, let's swap the container/section hierarchy wherever it appears in the code.

**Comment by brucecrevensten** [comment]
This is largely finished throughout the app, closing.
