### ISSUE TITLE
Investigate cause / validity of a few specific pixels from WRF output on the North Slope

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#69]
More details TBD, but there's a few pixels which seem to be discontinuous relative to their surrounding values in the North Slope.  Ask the downscaling team about this re: WRF outputs.

**Comment by charparr** [comment]
The funky water mask is another chapter in the SagaOfWRF™️ and based upon the following I am going to close this issue:
 - We raised the issue to the downscaling group and the reaction was a collective "meh"
 - There is no fix, short of running some type of Gaussian filter other resampling technique across the dataset, but that path leads to a world of vicious pain
 - We cannot just reprocess + fix
 - Kyle heroically led the WRF repair, and that process is complete, and the WRF data are as quality as they'll ever be
 - Eventually we'd hope to supersede all this stuff with CMIP6 or other daily data (NCAR 12 km)
