### ISSUE TITLE
Error with hydration noted in console

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/arctic-eds#74]
In the console in dev mode we see ``.

[This site](https://blog.lichter.io/posts/vue-hydration-error/) has a pretty good overview of what might be going wrong and how to fix.

This shouldn't actually matter since the app is targeted to be static only, but it'd be nice to identify the source of this error (we don't have it with our other Nuxt apps).

**Comment by cstephen** [comment]
I have not been able to replicate this issue. I'm running from the `main` branch and launching in development mode like this:

```
export NODE_ENV=development
npm run dev
```

But I'm not seeing any errors related to hydration in the console. Did this issue fix itself since the ticket was created, maybe?
